
- name: daemon reload
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker

- name: restart docker
  systemd:
    state: restarted
    name: docker

- name: apt update
  apt:
    update_cache: yes
